//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jgs.Framework.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jgs.Framework.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez přihlášení.
        /// </summary>
        public static string AnonymousButtonLabel {
            get {
                return ResourceManager.GetString("AnonymousButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymní přístup. Bez přihlášení.
        /// </summary>
        public static string AnonymousButtonTooltip {
            get {
                return ResourceManager.GetString("AnonymousButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string BrowseButtonLabel {
            get {
                return ResourceManager.GetString("BrowseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procházet.
        /// </summary>
        public static string BrowseButtonLabelTooltip {
            get {
                return ResourceManager.GetString("BrowseButtonLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit.
        /// </summary>
        public static string CloseTagTooltip {
            get {
                return ResourceManager.GetString("CloseTagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole nesmí být prázdné.
        /// </summary>
        public static string FieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("FieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složka|\n.
        /// </summary>
        public static string FolderFilter {
            get {
                return ResourceManager.GetString("FolderFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit.
        /// </summary>
        public static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte jméno nebo e-mail.
        /// </summary>
        public static string LoginTooltip {
            get {
                return ResourceManager.GetString("LoginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny soubory|*.*.
        /// </summary>
        public static string OpenDialogDefaultFilter {
            get {
                return ResourceManager.GetString("OpenDialogDefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to První stránka.
        /// </summary>
        public static string PN_First {
            get {
                return ResourceManager.GetString("PN_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední stránka.
        /// </summary>
        public static string PN_Last {
            get {
                return ResourceManager.GetString("PN_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další stránka.
        /// </summary>
        public static string PN_Next {
            get {
                return ResourceManager.GetString("PN_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předchozí stránka.
        /// </summary>
        public static string PN_Previous {
            get {
                return ResourceManager.GetString("PN_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamatovat.
        /// </summary>
        public static string RemeberLabel {
            get {
                return ResourceManager.GetString("RemeberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamatovat si přihlášení.
        /// </summary>
        public static string RememberTooltip {
            get {
                return ResourceManager.GetString("RememberTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načítám....
        /// </summary>
        public static string SuggestionInputLoadingContent {
            get {
                return ResourceManager.GetString("SuggestionInputLoadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nic nenalezeno.
        /// </summary>
        public static string SuggestionInputNotFoundText {
            get {
                return ResourceManager.GetString("SuggestionInputNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte text.
        /// </summary>
        public static string SuggestionInputWatermark {
            get {
                return ResourceManager.GetString("SuggestionInputWatermark", resourceCulture);
            }
        }
    }
}
